export enum States {
  ApiDocs = 'apiDocs',
  ApiResourcesIndex = 'apiResourcesIndex',
  AppUiMode = 'appUiMode',
  AppNavigationDrawerVisible = 'appNavigationDrawerVisible',
  AppResourcePageState = 'appResourcePageState',
  AppResourcePagePagination = 'appResourcePagePagination',
  AppResourceFilter = 'appResourceFilter',
  AppSnackbar = 'appSnackBar',
  LoginRedirectFrom = 'loginRedirectFrom',
  SearchParentKey = 'searchParentKey',
  GlobalSequence = 'globalSequence',
  NavigationFrom = 'navigationFrom',
  UserPlainPassword = 'userPlainPassword',
}
